print("There is good!")
#print(abs(-99))
shop = str(input("Please enter you dream item: "))
print(shop)
shopp = str(input("You dream price:"))
print(shopp)
money = str(input("You have money now?: "))
print(money)
